# Generated by Django 5.0.4 on 2024-04-23 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_mymodel_profile_my_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('summary', models.CharField(max_length=100, verbose_name='краткое описание')),
                ('full_content', models.TextField(verbose_name='полное описание')),
                ('price', models.FloatField(verbose_name='цена')),
                ('quantity', models.IntegerField(verbose_name='количество на складе')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_comment', models.TextField(verbose_name='Комментарий')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='main.product')),
            ],
        ),
    ]
