# Generated by Django 5.0.4 on 2024-04-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_comment', models.TextField(verbose_name='оценка')),
                ('oven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oven', to='main.product')),
            ],
        ),
    ]
