# Generated by Django 5.0.4 on 2024-04-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_oven'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oven',
            name='my_comment',
        ),
        migrations.AddField(
            model_name='oven',
            name='my_oven',
            field=models.IntegerField(default=1, verbose_name='оценка'),
            preserve_default=False,
        ),
    ]
